# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish

on:
  push:
    tags:
      - '*'
      - '!*-test'
    branches:
      - vaerktojer

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # PUBLISH
  ###################################################

  build:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup .NET SDKs (net8.0, global.json)
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json
          dotnet-version: 8.0.x

      - name: Publish
        shell: bash
        run: |
          dotnet tool restore
          dotnet make publish --nuget-key="${{secrets.NUGET_API_KEY}}"
